### ISSUE TITLE
redis_role consistency for replicas

### ISSUE THREAD

**Issue by aogereau** [claranet/ansible-role-redis#2]
## Expected Behavior

in the redis.conf template, it is indicated that the redis_role variable for all replicas should be "replica"
it should be the same value that is indicated in the Readme.md

## Current Behavior

https://github.com/claranet/ansible-role-redis/blob/main/templates/etc/redis/redis.conf.j2 line 291 , replicas has redis_role = replica
https://github.com/claranet/ansible-role-redis/blob/main/README.md , lines 120 - 122 - 150 and 152 replicas have redis_role = slave
For consistency sake, the value of redis_role should be se same in both cases

## Possible Solution

in Readme.md , replace bloc from lines 107 to 153 by the following : 

* #### Master replica scenario

**inventory**

```yaml
---
all:
  children:
    redis:
      hosts:
        master:
          redis_role: master
        replica-01:
          redis_role: replica
        replica-02:
          redis_role: replica
```

**playbook**

```yaml
---
- hosts: all
  vars:
    redis_sentinel_enabled: false
    redis_server_version: latest
  roles:
    - role: claranet.redis
```

* #### Sentinel scenario

**inventory**

```yaml
---
all:
  children:
    redis:
      hosts:
        master:
          redis_role: master
        replica-01:
          redis_role: replica
        replica-02:
          redis_role: replica
```

or , in redis.conf template , change the value of redis_role from replica to slave 

```
{% if redis_role is defined and redis_role == "slave" %}
replicaof {{ _redis_master_ip }} {{ redis_server_port }}
{% endif %}
```

## Context
This will cause problems when setting up a Redis cluster . If people follow the readme, the replicas will not be properly configured
